# Example AIP Policy Manifest
#
# This file defines what tools an agent is allowed to use.
# The AIP proxy loads this file at startup and enforces these rules
# on every tool/call request.
#
# Usage:
#   aip-proxy --target "python mcp_server.py" --policy examples/agent.yaml
#
# For monitor mode (dry-run), set spec.mode: monitor
# This logs violations but allows requests through for testing policies.

apiVersion: aip.io/v1alpha1
kind: AgentPolicy

metadata:
  name: code-review-agent
  version: "1.0.0"
  owner: platform-team@company.com

spec:
  # Policy enforcement mode:
  #   - "enforce" (default): Block violations, return error to client
  #   - "monitor": Log violations but allow through (dry-run mode)
  #
  # Monitor mode is useful for:
  #   - Testing new policies before enforcement
  #   - Understanding agent behavior in production
  #   - Gradual policy rollout
  mode: enforce

  # Tools that this agent is allowed to invoke.
  # Any tool not in this list will be blocked with a -32001 Forbidden error.
  #
  # Tool names should match exactly what the MCP server reports in tools/list.
  # Common patterns:
  #   - github_get_repo, github_list_pulls, github_create_review
  #   - postgres_query
  #   - slack_post_message
  allowed_tools:
    # GitHub read operations
    - github_get_repo
    - github_list_pulls
    - github_get_pull
    - github_list_commits
    
    # GitHub write operations (limited)
    - github_create_review
    - github_add_comment
    
    # Filesystem operations (read-only)
    - read_file
    - list_directory
    
    # Explicitly NOT allowed (for reference):
    # - github_delete_repo      # Destructive
    # - github_push             # Write to repo
    # - postgres_query          # Database access
    # - slack_post_message      # External communication
    # - exec_command            # Arbitrary code execution

  # Tool Rules: Fine-grained control per tool
  #
  # Each rule can specify:
  #   - action: "allow" (default), "block", or "ask"
  #   - allow_args: Regex patterns for argument validation
  #
  # Action types:
  #   - "allow": Permit the tool call (subject to arg validation)
  #   - "block": Deny the tool call unconditionally
  #   - "ask":   Prompt user via native OS dialog for approval (Human-in-the-Loop)
  #
  # The "ask" action spawns a native dialog box asking the user to
  # Approve or Deny. If the user doesn't respond within 60 seconds,
  # the request is auto-denied (fail-closed behavior).
  tool_rules:
    # Example: Dangerous tool requires explicit user approval
    - tool: dangerous_tool
      action: ask

    # Example: Shell execution requires approval AND argument validation
    - tool: exec_command
      action: ask
      allow_args:
        command: "^(ls|cat|echo|pwd)\\s.*"  # Only safe read-only commands

    # Example: Database queries allowed but only SELECT statements
    - tool: postgres_query
      action: allow
      allow_args:
        query: "^SELECT\\s+.*"

    # Example: Explicitly block destructive operations
    - tool: github_delete_repo
      action: block

    - tool: drop_table
      action: block

  # DLP (Data Loss Prevention) - Output Redaction
  #
  # The DLP scanner inspects tool responses (downstream) for sensitive data
  # and redacts matches before forwarding to the client. This prevents
  # accidental exposure of PII, API keys, and secrets through tool outputs.
  #
  # When a pattern matches, the sensitive data is replaced with:
  #   [REDACTED:<RuleName>]
  #
  # Each redaction is logged to the audit trail as a DLP_TRIGGERED event.
  dlp:
    # enabled: true  # Default is true when dlp block is present
    patterns:
      # Email addresses (PII)
      - name: "Email"
        regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"

      # AWS Access Key IDs (starts with AKIA, ASIA, etc.)
      - name: "AWS Key"
        regex: "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"

      # Generic secret patterns (api_key, secret, password with values)
      - name: "Generic Secret"
        regex: "(?i)(api_key|secret|password)\\s*[:=]\\s*['\"]?([a-zA-Z0-9-_]+)['\"]?"

      # Social Security Numbers (US)
      - name: "SSN"
        regex: "\\b\\d{3}-\\d{2}-\\d{4}\\b"

      # Credit Card Numbers (basic pattern - 16 digits with optional separators)
      - name: "Credit Card"
        regex: "\\b(?:\\d{4}[- ]?){3}\\d{4}\\b"

      # GitHub Personal Access Tokens
      - name: "GitHub Token"
        regex: "ghp_[a-zA-Z0-9]{36}"

      # Private keys (PEM format headers)
      - name: "Private Key"
        regex: "-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"
